### ISSUE TITLE
python so problem

### ISSUE THREAD

**Issue by moyaying** [crystax/android-platform-ndk#23]
06-24 19:37:45.123 14477-14477/com.jventura.pyapp I/pybridge:   File "/data/data/com.jventura.pyapp/assets/python/stdlib.zip/socket.py", line 49, in <module>
06-24 19:37:45.123 14477-14477/com.jventura.pyapp I/pybridge: ImportError: dlopen failed: cannot locate symbol "__cxa_atexit" referenced by "_socket.so"...

06-24 19:35:32.533 14095-14095/com.jventura.pyapp I/pybridge: Traceback (most recent call last):
06-24 19:35:32.533 14095-14095/com.jventura.pyapp I/pybridge:   File "<string>", line 1, in <module>
06-24 19:35:32.533 14095-14095/com.jventura.pyapp I/pybridge:   File "/data/data/com.jventura.pyapp/assets/python/bootstrap.py", line 9, in <module>
06-24 19:35:32.543 14095-14095/com.jventura.pyapp I/pybridge:     import ssl
06-24 19:35:32.543 14095-14095/com.jventura.pyapp I/pybridge:   File "/data/data/com.jventura.pyapp/assets/python/stdlib.zip/ssl.py", line 98, in <module>
06-24 19:35:32.543 14095-14095/com.jventura.pyapp I/pybridge: ImportError: dlopen failed: cannot locate symbol "__cxa_atexit" referenced by "_ssl.so"...
06-24 19:35:32.543 14095-14095/com.jventura.pyapp I/pybridge: Call into Python interpreter

In some device run crash, the crash device  cpu type is armeabi-v7a.
All so is copy from https://dl.crystax.net/ndk/darwin/919/...

**Comment by bobpoekert** [comment]
Do you have libcrystax.so in your library path?
